### ISSUE TITLE
IP machine tags can reference machines that were freed

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-api#13]
In prod, we encountered the following state:

```
metalctl -c ~/.metalctl/prod.yaml network ip ls --project 4867702a-a529-45c9-b150-7913d5b8ff88
  IP            NAME                            NETWORK                               PROJECT                               TYPE       TAGS                                          
  10.3.28.3     shoot--p66jb...-56595cb69vx5pc  8ddde75f-9c27-4f85-8593-4de62896a6b5  4867702a-a529-45c9-b150-7913d5b8ff88  ephemeral  machine:eff49e00-6ff4-11e9-8000-efbeaddeefbe  
  10.3.28.4     shoot--p66jb...-56595cb698clpw  8ddde75f-9c27-4f85-8593-4de62896a6b5  4867702a-a529-45c9-b150-7913d5b8ff88  ephemeral  machine:eff49e00-6ff4-11e9-8000-efbeaddeefbe  
  10.3.28.5     shoot--p66jb...-75cc5f54bg6xp7  8ddde75f-9c27-4f85-8593-4de62896a6b5  4867702a-a529-45c9-b150-7913d5b8ff88  ephemeral  machine:00000000-0000-0000-0000-ac1f6b7bed20  
  10.3.44.3     shoot--p66jb...cb7fdc8cb-99wjv  e6ed6a23-d4c7-4aef-9fc7-512c6637436c  4867702a-a529-45c9-b150-7913d5b8ff88  ephemeral  machine:eff49e00-6ff4-11e9-8000-efbeaddeefbe  
  10.3.44.4     shoot--p66jb...cb7fdc8cb-zc69q  e6ed6a23-d4c7-4aef-9fc7-512c6637436c  4867702a-a529-45c9-b150-7913d5b8ff88  ephemeral  machine:eff49e00-6ff4-11e9-8000-efbeaddeefbe  

metalctl -c ~/.metalctl/prod.yaml machine ls --id eff49e00-6ff4-11e9-8000-efbeaddeefbe
  ID                                         LAST EVENT   WHEN  AGE     HOSTNAME    PROJECT                               SIZE           IMAGE       PARTITION  
  eff49e00-6ff4-11e9-8000-efbeaddeefbe       Phoned Home  27s   6h 51m  firewall01  17022797-89e6-4fbc-a9ed-cf62d17b67b2  c1-xlarge-x86  Firewall 1  nbg-w8101  
4200035841
```

We can see that the ephemeral IPs of project A point to a machine allocated by project B, which is an invalid state.

As this was affecting the production control plane and cluster reconciliation, I manually resolved this issue by deleting the five ephemeral addresses by hand.

However, the question how this could happen should be investigated.

```

metalctl -c ~/.metalctl/prod.yaml machine describe eff49e00-6ff4-11e9-8000-efbeaddeefbe
allocation:
    consolepassword: bO1pJr0KrtICn++q
    created: "2019-11-11T06:52:51.934Z"
    description: ""
    hostname: firewall01
    image:
        changed: "2019-11-08T11:32:44.307Z"
        created: "2019-11-07T13:21:26.973Z"
        description: Firewall 1
        features:
          - firewall
        id: firewall-1
        name: Firewall 1
        url: http://192.168.2.1:9000/metal/images/os/firewall/1/img.tar.lz4
    name: ""
    networks:
      - asn: 4200035841
        destinationprefixes: []
        ips:
          - 10.2.0.2
        nat: false
        networkid: underlay-nbg-w8101
        prefixes:
          - 10.2.0.0/24
        private: false
        underlay: true
        vrf: 0
      - asn: 4200035841
        destinationprefixes:
          - 0.0.0.0/0
        ips:
          - 212.34.89.18
        nat: true
        networkid: internet-nbg-w8101
        prefixes:
          - 212.34.89.0/24
        private: false
        underlay: false
        vrf: 104009
      - asn: 4200035841
        destinationprefixes: []
        ips:
          - 10.3.140.1
        nat: false
        networkid: 8f1e8770-d513-43b6-ab38-a7caef724441
        prefixes:
          - 10.3.140.0/22
        private: true
        underlay: false
        vrf: 52
    project: 17022797-89e6-4fbc-a9ed-cf62d17b67b2
    sshpubkeys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvtjburiTPwAxEG+jkH6Cx6jqUxsTSbTC4uMXFW9f59gbTHnPU7H+nLcEdSab2eGbuF2djkn/uVftp3x84zTk7c/PXgcvWHyC1yaGsWINc5PPygtMEv29vB4TlGKeGY3M0TfN+0GzzjBWzRV/+w8/UuIieBeqGSV9HyDuj6hnHktLamYRuDw1UPhvg7GsPQW+NrEU/dH0GL5wkyJGR/VEsLlgpM23Lq1tEv8Vgy0PBb/RireqXIwOinN7ue7e02jhuy/eSC3U5kthKp6ge2vGcF+uleN9qKYlX5ypVjTXZDS4A5NIFt1ZqZnzC5lDXSZQvXzfHyFgUxTKwqa4HIZPD
        devops@T480
    succeeded: false
    userdata: ""
changed: "2019-11-11T06:53:32.936Z"
created: "2019-11-07T13:16:21.992Z"
description: ""
events:
    incompleteprovisioningcycles: "0"
    lasteventtime: "2019-11-11T13:44:51.483Z"
    log:
      - event: Phoned Home
        message: provisioned since 2019-11-11T06:53:15Z
        time: "2019-11-11T06:54:00.898Z"
      - event: Booting New Kernel
        message: booting into distro kernel
        time: "2019-11-11T06:53:33.433Z"
      - event: Installing
        message: start installation
        time: "2019-11-11T06:52:57.407Z"
      - event: Waiting
        message: waiting for installation
        time: "2019-11-10T13:49:39.666Z"
      - event: Registering
        message: start registering
        time: "2019-11-10T13:49:37.355Z"
hardware:
    cpucores: 24
    disks:
      - name: nvme0n1
        size: 1600321314816
      - name: nvme1n1
        size: 1600321314816
      - name: sda
        size: 63350767616
    memory: 101633560576
    nics:
      - mac: ac:1f:6b:7b:78:b2
        name: eth0
      - mac: ac:1f:6b:7b:78:b3
        name: eth1
      - mac: "00:00:00:00:00:00"
        name: lo
id: eff49e00-6ff4-11e9-8000-efbeaddeefbe
ledstate:
    description: Machine registered
    value: LED-OFF
liveliness: Alive
name: ""
partition:
    bootconfig:
        commandline: console=ttyS1,115200n8 ip=dhcp carrier_timeout=10
        imageurl: https://blobstore.fi-ts.io/metal/images/metal-hammer/metal-hammer-initrd.img.lz4
        kernelurl: https://blobstore.fi-ts.io/metal/images/metal-hammer/stable/metal-hammer-kernel
    changed: "2019-11-08T11:32:44.424Z"
    created: "2019-11-07T13:21:27.068Z"
    description: Metal Prod environment in Nuremberg W8101
    id: nbg-w8101
    mgmtserviceaddress: nbg-w8101-mgmt-service:2222
    name: Nuremberg W8101
    privatenetworkprefixlength: 22
rackid: nbg-w8101-rack01
size:
    changed: "2019-11-08T11:32:44.859Z"
    constraints:
      - max: 24
        min: 16
        type: cores
      - max: 120000000000
        min: 80000000000
        type: memory
      - max: 4000000000000
        min: 500000000000
        type: storage
    created: "2019-11-07T13:21:27.549Z"
    description: Compute for the very large masses
    id: c1-xlarge-x86
    name: c1-xlarge-x86
state:
    description: ""
    value: ""
tags:
  - machine.metal-pod.io/rack=nbg-w8101-rack01
  - machine.metal-pod.io/chassis=C217BAI04P20057
  - machine.metal-pod.io/network.primary.asn=
```
